notifications: # set notification options
  email:
    recipients:
      - alexgre@ufl.edu
    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
  # Or we could just disable all email
  # email: false

language: python

#to use docker sudo must be required
sudo: required

python:
  - "3.6"
# script: python myunittestp.py

install: 
  - pip install -r requirements.txt
  - pip install awscli --upgrade

#set up database: mongodb 
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
    #add chrome for selenium test
    #chrome: stable


services:
   - mongodb
# jobs:
#   include:
#     - stage: test

before_script:
  - export PATH=~/.local/bin:$PATH
  - sleep 15
  - eval $(aws ecr get-login --region us-east-1)
#default will be changed to "trusty" (Ubuntu trusty 14.02) later
dist: "precise"

script:

      # - python myunittestp.py
      # - python myunittestq.py
      - nosetests -w tests myunittestq myunittestp mynosetest testwithmock test_with_mongodb test_flask -v --with-id

# matirx:
#   include:
#     - python: 3.6
#     script: python myunittestp.py

#     - python: 3.6
#     script: python myunittestq.py

after_script:
  - pkill mongod

