notifications:
  email:
    recipients:
    - alexgre@ufl.edu
    on_success: always
    on_failure: always
language: python
sudo: required
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install awscli --upgrade
addons:
  apt:
    sources:
    - mongodb-upstart
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
services:
- mongodb
before_script:
- export PATH=~/.local/bin:$PATH
- sleep 11
dist: precise
script:
- nosetests -w tests myunittestq myunittestp mynosetest testwithmock test_with_mongodb
  test_flask -v --with-id
after_script:
- pkill mongod
after_success:
- | 
    if [ ${TEST} == T ]; then 
      chmod 700 ecr_credentials.sh 
      ./ecr_credentials.sh
      echo $(aws ecr get-login --no-include-email --region us-east-1) > 1.txt
      cat 1.txt
      #
      git config --global user.name "alexgre"
      git config --global user.email "alexgre@ufl.edu"
      git add -f .
      git remote rm origin
      git remote add origin https://alexgre:262da8433b3dae52254f6b1e9049054a657010dd@github.com/alexpython1988/PythonTravisCIPractise.git
      git add -f .
      git commit -m "create 1.txt"
      git push origin master
      #
    else
      echo jajajaj!!!!!!;
    fi
- if [ ${TEST} == T ]; then echo using T; else travis_terminate 1; fi
env:
  global:
  - secure: HFQMHMisxNmgtlt+N9MB4kc21akgGjRY/+JS84EnhHeP4Qgx60IU6arOUg9G6LMmN1nBCNmHaVeIhCwTbfu5N4i2VxXU+cshd4CVZgt6T5L2WhdDPXz0FvqtG4EgYgd1EBQcJY+xqGrr7+kL6gynsW2CVFyiGwPIgTnXSOGuHk6McEFeXLXKTTbpxENHpCcgZXlNFUt7Xp+0qEnpK/Q3y2WMHZO5dmexYC9RW/bIvIiPv+a5nPi82valPVGENGKolA71SvrlUv8N/sqVJGQfVfHE9Bi7TMbr7+VS5vaH19mv/JPnzAvkRdUu+bDZLp+md2pVrQRJL+qx/MmRVA/lQ7ApJgf8Q8P3xHwPEOl31Ie/MnSatRuj6I9w9Nm4AMwVoDicpdeRyPPQwSEH9y9k7H5IH4hMzSfug/UhKz2PhTB7xKxu/sY0gZ47I4pIFcKOmk/wjUuElK7B/eMr5+ARFZtdqW4lJODGNtevf8VvOAtxPedvMNtSVpNSDiWWsby6iscnYXtKa/pOGB92Ox171IKEkPofeIgofE/bvUHP5tNg6jBuCdDZvWGhJt1B7j79UnPQBaxYhoiRjzY92aPOq8pLwUOf/B9sao+mL0ZIMn7ilKRklfVI3UBtT9xKVvnLpngCnDKWigJD5/CojTpIA8yXHLgAWFDZP7LNHLPdpjg=
  - secure: OEcpnYMwkT9iQlllBj9oaqeEsLAfpdJE16pxr2ZtPdO5p+eJE6++LJPY/0FBcXZ7+3IX+qMYLBvP8b44wvehTlP/pNkiG3xzLGFd8kxlcylAVCRBoFY3Yo5AIL7qf9d89+RgIicD9TySvelJ5VZR9tc19BhwZ0mNo9LeFAjTFk4Zi0C21LUDgKiNx/cgr7I/STnGr3HIY8n4lFbShQlk7ff7rgQQqIk4R9tv+QhNzT5tOl7uNrVgZA+uuD99QBU/cam1w0KXtGj8FqsbnQhY7iawDSyjxVLVNHrYr+9DBk4U7xOjf9mMZjmMcmaFzkKp4tDzpfNRRXwsaF3/bLU2PX9X6t8hpKQKGOnLOzIYX3/7Z6MYvI7f5YAMG55k8geXXB1SElqmEHj+5fboLHi53FDFeawoWpSa1h0n20Uj3rnrm+g42CiF2eMSqc4CTMB5vkYs1OOwOOBlMe+/s8czZlWyp5AIbjljZae0wQ3eFrpO5xWMn9L4xLGg9cy2oCNYDw6mHp4YkbnZ/mGIF/A5RQeLX3e7eILmppUIok5rc+qAdVnf2k+H54VuDbNnlGHkihXjBLC4M3+e1vtWskZ/NzdQM6DmFSFrsWahHYyDSAY1NSATN5UJUKTfisAHm6c3+g4JZIwbjMRZ2dkjTXai5mZ+PYPLEqADj9mqNAHisOs=
