notifications: # set notification options
  email:
    recipients:
      - alexgre@ufl.edu
    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
  # Or we could just disable all email
  # email: false

language: python

sudo: false

python:
  - "3.3"
  - "3.6"
# script: python myunittestp.py

install: pip install --user -r requirements.txt

# jobs:
#   include:
#     - stage: test
script: 
      # - python myunittestp.py
      # - python myunittestq.py
      - nosetests -w tests myunittestq myunittestp mynosetest testwithmock -v --with-coverage

# matirx:
#   include:
#     - python: 3.6
#     script: python myunittestp.py

#     - python: 3.6
#     script: python myunittestq.py