notifications: # set notification options
  email:
    recipients:
      - alexgre@ufl.edu
    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
  # Or we could just disable all email
  # email: false

language: python

sudo: false

python:
  - "3.6"
# script: python myunittestp.py

install: pip install -r requirements.txt

#set up database: mongodb 
# services:
#   - mongodb

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
  packages:
      - mongodb-org

# jobs:
#   include:
#     - stage: test
before_script:
  - sleep 15

script: 
      # - python myunittestp.py
      # - python myunittestq.py
      - nosetests -w tests myunittestq myunittestp mynosetest testwithmock test_with_mongodb -v --with-coverage

# matirx:
#   include:
#     - python: 3.6
#     script: python myunittestp.py

#     - python: 3.6
#     script: python myunittestq.py

after_script:
  - pkill mongod